services:
  - type: web
    name: evilworker-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node proxy_server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
